"""empty message

Revision ID: 528b52d24c8f
Revises: fbe8dc728c13
Create Date: 2021-03-18 10:43:28.802832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528b52d24c8f'
down_revision = 'fbe8dc728c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('filename', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'filename')
    # ### end Alembic commands ###
